export type addResourceFormField = {
  resource_name: string;
  resource_type: number;
  disorder_id: string;
  model_id: string;
  category_id: string;
  resource_desc: string;
  resource_instruction: string;
  resource_references: string;
  agenda_id: string;
  file_name: string;
  resource_avail_admin: number;
  resource_avail_therapist: number;
  resource_avail_onlyme: number;
  resource_avail_all: number;
  uploadFile: File;
  uploadFileURL: string;
};

export type editResourceFormField = {
  _id: string;
  resource_name: string;
  resource_type: string;
  disorder_id: string;
  model_id: string;
  category_id: string;
  resource_desc: string;
  resource_instruction: string;
  resource_references: string;
  agenda_id: string;
  file_name: string;
  resource_avail_admin: number;
  resource_avail_therapist: number;
  resource_avail_onlyme: number;
  resource_avail_all: number;
  uploadFile?: File;
  uploadFileURL?: string;
  resource_url?: null;
  download_resource_url?: string;
  disorder_detail: Object;
  model_detail: Object;
};
