module.exports = {
  preset: 'ts-jest',
  testRunner: 'jest-jasmine2',
  roots: ['<rootDir>'],
  transform: {
    '^.+\\.(ts|tsx)?$': 'ts-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  globals: {
    'ts-jest': {
      babelConfig: true,
    },
  },
  testMatch: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[jt]s?(x)'],
  testPathIgnorePatterns: ['<rootDir>/dist/'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '\\.(scss|sass|css)$': 'identity-obj-proxy',
  },
  clearMocks: true,
  collectCoverage: false,
  coverageDirectory: '<rootDir>/coverage',
  collectCoverageFrom: [
    '<rootDir>/**/*.[t]s?(x)',
    '!<rootDir>/.next/',
    '!<rootDir>/coverage/',
    '!<rootDir>/**/__tests__/',
    '!<rootDir>/**/__mocks__/',
    '!<rootDir>/node_modules/',
    '!<rootDir>/test-reports/',
    '!<rootDir>/.storybook/',
    '!<rootDir>/out/',
  ],
  coveragePathIgnorePatterns: [
    '.test.tsx',
    '.test.ts',
    '.spec.tsx',
    '.spec.ts',
    '.stories.tsx',
    '.stories.ts',
    'node_modules',
    '.d.ts',
    '.prettierrc.js',
    '.config.js',
    '.storybook',
    'coverage',
    '.next',
    'build',
    'style-dictionary',
    'generated',
  ],
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/setup-tests.ts'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  coverageReporters: ["json", "lcov", "text"],
};
